### ISSUE TITLE
Document Purpose

### ISSUE THREAD

**Issue by chanr1atwit** [chanr1atwit/AtmosphericBG#4]
Describe in depth what the document goes over(eg system architecture, design, etc)

Due on 5/30/2022

[Link to Miro ticket (you will need to manually expand)](https://miro.com/app/board/uXjVOy8bsTw=/?moveToWidget=3458764526098896687&cot=14)

**Comment by leixatwit** [comment]
Wrote the document purpose. Requesting a peer review.

**Comment by salterdatwit** [comment]
The Document Purpose section looks fine. Closing the issue.
