### ISSUE TITLE
Product Overview

### ISSUE THREAD

**Issue by chanr1atwit** [chanr1atwit/AtmosphericBG#5]
Fill in the Product Overview section of the Software Design document

Due on 5/30/2022

[Link to Miro ticket (you will need to manually expand)](https://miro.com/app/board/uXjVOy8bsTw=/?moveToWidget=3458764526127053072&cot=14)

**Comment by leixatwit** [comment]
Wrote the product overview. Requesting a peer review.

**Comment by salterdatwit** [comment]
Looks good. Closing.
